### ISSUE TITLE
missing car:KOENIGSEGG JESKO

### ISSUE THREAD

**Issue by 10101abc** [embedisbae/FH4-Car-ID-List#1]
The 2020 Koenigsegg Jesko is a RWD extreme track toy by Koenigsegg.

**Comment by addidotlol** [comment]
The list is pretty outdated, I'll try to add this one though. Do you know the ID it should be?

**Comment by 10101abc** [comment]
> The list is pretty outdated, I'll try to add this one though. Do you know the ID it should be?

sorry i really dont know, that's why i came here by google search.
pity

**Comment by hekawa** [comment]
Hello, can you please tell me how can I find IDs of each machine? Here, some machines are missing from the list and I would like to know in which files or in what way i can find IDs

**Comment by Tinase-nau** [comment]
Jesko is 3315

You can find IDs from "Forza Horizon 4\media\audio\cars\CarEventMapping.xml", id is behind the attribute "ordinal"

You can write an up-to-date table with the info from "CarEventMapping.xml"

**Comment by addidotlol** [comment]
> Jesko is 3315
> 
> You can find IDs from "Forza Horizon 4\media\audio\cars\CarEventMapping.xml", id is behind the attribute "ordinal"
> 
> You can write an up-to-date table with the info from "CarEventMapping.xml"

do u think you could send that file over?

**Comment by Tinase-nau** [comment]
> > Jesko is 3315
> > You can find IDs from "Forza Horizon 4\media\audio\cars\CarEventMapping.xml", id is behind the attribute "ordinal"
> > You can write an up-to-date table with the info from "CarEventMapping.xml"
> 
> do u think you could send that file over?

[CarEventMapping.zip](https://github.com/embedvr/FH4-Car-ID-List/files/9977622/CarEventMapping.zip)

**Comment by WayneMcCullough** [comment]
<Car friendlyName="KOE_Jesko_20" ordinal="3315" forzavistaPath="/Master/Forzavista/Components/VerticalDoors_02/" forzavistaBank="GLB_Forzavista">
ID Cars "JESKO" 3315
When trying to get this Cheat Engin car,
the game freezes.

**Comment by Tinase-nau** [comment]
> ID Cars "JESKO" 3315 When trying to get this Cheat Engin car, the game freezes.

The method to insert a car is destructive. You need to delete as many irrelevant memory addresses from the list as possible. When searching for the id of the car to replace, search for "unchanged values" multiple times until no more red colored values appear. Also turn game graphics down to minimum. But even then the id address may be of something else and overwriting it may crash the game. It's even harder to replace a car when the id is 3 digits. But I got almost all I wanted. If the game crashes, try again and again. May take 10+ tries in worst cases. Also keep in mind that some cars have lock check and can only be obtained by satisfying very special condition first, like for e.g. purchase of 10m cred house, so check wiki for stubborn cars.

**Comment by addidotlol** [comment]
This repo is not maintained, and I am unable to maintain it. 
[55c31b4](https://github.com/embedvr/FH4-Car-ID-List/commit/55c31b4dce5fd8fb2dfdb7f461b22435ed5494c9) adds a warning to the readme, and other issues will be revolved with a reference to https://github.com/embedvr/FH4-Car-ID-List/issues/1#issuecomment-1306840568.

**Comment by Phaross** [comment]
what's id of amg hammer coupe 1987?

**Comment by Tinase-nau** [comment]
> what's id of amg hammer coupe 1987?

3176

**Comment by Phaross** [comment]
> > what's id of amg hammer coupe 1987?
> 
> 3176

how do you know this

**Comment by Tinase-nau** [comment]
> > > what's id of amg hammer coupe 1987?
> > 
> > 
> > 3176
> 
> how do you know this

https://github.com/embedvr/FH4-Car-ID-List/issues/1#issuecomment-1306840568

**Comment by Phaross** [comment]
> > > > what's id of amg hammer coupe 1987?
> > > 
> > > 
> > > 3176
> > 
> > 
> > how do you know this
> 
> [#1 (comment)](https://github.com/embedvr/FH4-Car-ID-List/issues/1#issuecomment-1306840568)

Some cars are not included in car event mapping

**Comment by Phaross** [comment]
> > > > what's id of amg hammer coupe 1987?
> > > 
> > > 
> > > 3176
> > 
> > 
> > how do you know this
> 
> [#1 (comment)](https://github.com/embedvr/FH4-Car-ID-List/issues/1#issuecomment-1306840568)

for example like amg hammer coupe

**Comment by Tinase-nau** [comment]
> > > > > what's id of amg hammer coupe 1987?
> > > > 
> > > > 
> > > > 3176
> > > 
> > > 
> > > how do you know this
> > 
> > 
> > [#1 (comment)](https://github.com/embedvr/FH4-Car-ID-List/issues/1#issuecomment-1306840568)
> 
> for example like amg hammer coupe

Oh yeah, 2 options:
a. If the car is DLC car, you maybe lack the DLC for the car. Check a FH4 wiki for car origin.
b. FH4's car model licenses are expiring; FH4 is pulled from the stores and certain car models have also been removed from the game.

**Comment by ARD12115** [comment]
I just wanted u to know that there's a missing code for a car
Car name:FIAT X1/9
year.         :1975
Available. :Horizon Backstage event

**Comment by ARD12115** [comment]
> I just wanted u to know that there's a missing code for a car Car name:FIAT X1/9 year. :1975 Available. :Horizon Backstage event

Code:1579
