### ISSUE TITLE
BMW

### ISSUE THREAD

**Issue by AdrianMD19** [embedisbae/FH4-Car-ID-List#4]
BMW 850CSi

**Comment by Frozed07** [comment]
I find it 1493

**Comment by AdrianMD19** [comment]
Thank you, anyway I found on the first issue the file where are all the missing cars

**Comment by addidotlol** [comment]
Repo is no longer maintained, please reference https://github.com/embedvr/FH4-Car-ID-List/issues/1#issuecomment-1306840568 to find IDs.
